name: Build and push Docker image

on:
  push:
    branches: [ "main" ]

jobs:
  push_to_registry:

    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        id: vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ vars.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: blagoy-secret/data/docker DOCKER_PASSWORD | DOCKER_PASSWORD
      
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Use secre
        run: |
          echo "My secret is: ${{ steps.vault.outputs.DOCKER_PASSWORD }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: $DOCKER_PASSWORD

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}
          tags: latest
          labels: latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  server_update:
    needs: push_to_registry
    name: Update server by ssh
    runs-on: ubuntu-latest
    steps:
      - name: Connect and run script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_stop: true
          script: bash /home/administrator/app/deploy.sh
