name: CI

on:
  push:
    branches:
      - main

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Get secret from Vault
        id: get_secret
        run: curl -s --header "X-Vault-Token: hvs.kPbIh5sh48nElqYCg8vM4loC" http://192.168.1.58:8200/v1/my-secret/data/docker
