name: CI

on:
  push:
    branches:
      - main

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get secret from Vault
        id: get_secret
        run: |
          # Получаем секрет из Vault
          SECRET_PATH="my-secret/data/docker"  # Укажите путь к вашему секрету
          RESPONSE=$(curl -s --header "X-Vault-Token: ${{ secrets.VAULT_TOKEN }}" ${{ vars.VAULT_ADDR }}/v1/my-secret/data/docker)

          # Извлекаем нужные данные из ответа
          DOCKER_PASSWORD=$(echo $RESPONSE | jq -r '.data.data.DOCKER_PASSWORD')

 #         echo "$DOCKER_PASSWORD"

 #         # Устанавливаем переменные окружения для использования в следующих шагах
 #         echo "DOCKER_PASSWORD=$DOCKER_PASSWORD" >> $GITHUB_ENV

 #     - name: Use secret
#        run: |
#          echo "My username is: $DOCKER_PASSWORD"
