name: Get Vault secrets

on:
  push:
    branches: ["main"]

jobs:
  get-vault-secret-job:
    runs-on: ubuntu-latest
    steps:
      - name: get secret
        id: vault
        #uses: hashicorp/vault-action@v2
        #with:
        #  url: ${{ vars.VAULT_ADDR }}
        #  token: ${{ secrets.VAULT_TOKEN }}
        #  secrets: |
        #    my-secret/data/docker DOCKER_PASSWORD
        run: | 
          export SECRET_JSON_DOCKER=$(curl -s --header "X-Vault-Token:$VAULT_TOKEN" $VAULT_ADDR/v1/my-secret/data/docker)
          echo "DOCKER_PASSWORD=$(echo $SECRET_JSON_DOCKER | jq -r '.data.data.DOCKER_PASSWORD')" >> $GITHUB_ENV
          echo "$DOCKER_PASSWORD"
              - name: create var

          echo "SERVER_IP=$(hostname -I)" >> $GITHUB_ENV
      - name: read var
        run: |
          echo "Calling var from env using env context: server ip is ${{ env.SERVER_IP }}"
          echo "Calling var from env: server ip is $SERVER_IP"

  use-vault-secret:
    needs: get-vault-secret-job
    runs-on: ubuntu-latest
    steps:
      - name: use secret
        run: echo "needs.vault.output.value"
