name: Get Vault secrets

on:
  push:
    branches: ["main"]

jobs:
  get-vault-secret-job:
    runs-on: ubuntu-latest
    steps:
      - name: get secret
        id: vault
        #uses: hashicorp/vault-action@v2
        #with:
        #  url: ${{ vars.VAULT_ADDR }}
        #  token: ${{ secrets.VAULT_TOKEN }}
        #  secrets: |
        #    my-secret/data/docker DOCKER_PASSWORD
        run: | 
          export SECRET_JSON_DOCKER=$(curl -s --header "X-Vault-Token:$VAULT_TOKEN" $VAULT_ADDR/v1/my-secret/data/docker)
          export DOCKER_PASSWORD=$(echo $SECRET_JSON_DOCKER | jq -r '.data.data.DOCKER_PASSWORD')
          echo DOCKER_PASSWORD
        

  use-vault-secret:
    needs: get-vault-secret-job
    runs-on: ubuntu-latest
    steps:
      - name: use secret
        run: echo "steps.vault.output.value"
