name: CI

on:
  push:
    branches:
      - main

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch secrets from Vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ vars.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            my-secret/data/docker
        id: vault

      - name: Use secret
        run: |
          echo "My secret is: ${{ steps.vault.outputs.DOCKER_PASSWORD}}"
