name: Get Vault secrets

on:
  push:
    branches: ["main"]

jobs:
  get-vault-secret-job:
    runs-on: ubuntu-latest
    steps:
      - name: get secret
        id: vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ vars.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          method: read
          path: my-secret/docker
          field: DOCKER_PASSWORD

  use-vault-secret:
    runs-on: ubuntu-latest
    steps:
      - name: use secret
        run: echo "steps.vault.output.value"
