name: get secret 
on:
  push:
    branches: 
      - master 
jobs:
  get-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ vars.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: blagoy-secret/data/docker DOCKER_PASSWORD

      - name: use secret 
        run: echo $DOCKER_PASSWORD
